baseURL = "https://andreiaoca.com"
title = "Andreia Oca"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Andreia Oca"
description = "Andreia Oca - personal blog"
author = "Andreia Oca"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
disableSpecial1stPost = false
comments = false
hidemeta = false
showtoc = false
tocopen = false

  [params.label]
  text = "Andreia Oca"
  icon = "/profile.jpeg"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Andreia Oca"
  subtitle = "Personal blog. Student. Tech Enthusiast. Trainer. Bookworm. Scout. Outdoorsy."

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Andreia Oca"
  Content = "Personal blog. Student. Tech Enthusiast. Trainer. Bookworm. Scout. Outdoorsy."

  [[params.socialIcons]]
  name = "facebook"
  url = "https://facebook.com/andreia.oca"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/andreia.oca"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/andreia-irina-ocanoaia/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/andreia-oca"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "home"
name = "Home"
url = "https://andreiaoca.com"
weight = 10

[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30

[[menu.main]]
identifier = "career"
name = "Career"
url = "/career/"
weight = 40

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 50
